spring:
  application:
    name: user-balance-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userbalancedb
    username: test
    password: test
    hikari:
      maximum-pool-size: 2
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db-changelog-master.yaml
    default-schema: public
    contexts: migrated
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
  elasticsearch:
    uris: http://localhost:9200
  config:
    import: 'optional:configserver:'
jwt:
  secret: c2Rmc2RmZHNmc2Rmc2RmZHNmc2Rmc2Rmsdffffffffsdfsdfsdf878787sd8f7s7df78sd87f78sdf87
  lifetime: 600m
security:
  permitted:
    urls: /user-balance-api/**
server:
  port: 8081
logging:
  level:
    -root: INFO
springdoc:
  api-docs:
    path: /user-balance-api/v3/api-docs
  swagger-ui:
    path: /user-balance-api/swagger-ui.html
openapi:
  service:
    url: http://localhost:8081


#spring:
#  application:
#    name: user-balance-api
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/userbalancedb
#    username: test
#    password: test
#    hikari:
#      maximum-pool-size: 2
#  management:
#    endpoints:
#      web:
#        exposure:
#          include: "*"
#  liquibase:
#    enabled: true
#    drop-first: true
#    change-log: classpath:db/changelog/db-changelog-master.yaml
#    default-schema: public
#    contexts: migrated
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: public
#  cache:
#    type: redis
##    redis:
##      host: localhost
##      port: 6379
##  redis:
##    host: ${SPRING_REDIS_HOST:localhost}
##    port: ${SPRING_REDIS_PORT:6379}
##
##  cache:
##      type: redis
#
#  # Elasticsearch
#  elasticsearch:
#      uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
#  config:
#    import: 'optional:configserver:'
#jwt:
#  secret: c2Rmc2RmZHNmc2Rmc2RmZHNmc2Rmc2Rmsdffffffffsdfsdfsdf878787sd8f7s7df78sd87f78sdf87
#  lifetime: 600m
#security:
#  permitted:
#    urls: /user-balance-api/**
#server:
#  port: 8081
#logging:
#  level:
#    -root: INFO
#springdoc:
#  api-docs:
#    path: /user-balance-api/v3/api-docs
#  swagger-ui:
#    path: /user-balance-api/swagger-ui.html
#openapi:
#  service:
#    url: http://localhost:8081

#spring:
#  application:
#    name: user-balance-api
#
#  config:
#    import: 'optional:configserver:'
#
#  # ─────────── PostgreSQL ───────────
#  datasource:
#    url:        ${SPRING_DATASOURCE_URL:jdbc:postgresql://userbalancedb:5432/userbalancedb}
#    username:   ${SPRING_DATASOURCE_USERNAME:test}
#    password:   ${SPRING_DATASOURCE_PASSWORD:test}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 5
#
#  # ─────────── JPA / Hibernate ───────────
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: public
#
#  # ─────────── Liquibase ───────────
#  liquibase:
#    enabled: true
#    drop-first: true
#    change-log: classpath:db/changelog/db-changelog-master.yaml
#
#  # ─────────── Redis ───────────
#  redis:
#    host: ${SPRING_REDIS_HOST:redis}
#    port: ${SPRING_REDIS_PORT:6379}
#
#  cache:
#    type: redis
#
#  # ─────────── Elasticsearch ───────────
#  elasticsearch:
#    uris: ${SPRING_ELASTICSEARCH_URIS:http://elasticsearch-balance:9200}
#
#  # ─────────── Actuator ───────────
#  management:
#    endpoints:
#      web:
#        exposure:
#          include: "*"
#
#server:
#  port: 8081
#
#jwt:
#  secret: c2Rmc2RmZHNmc2Rmc2RmZHNmc2Rmc2Rmsdffffffffsdfsdfsdf878787sd8f7s7df78sd87f78sdf87
#  lifetime: 600m
#
#security:
#  permitted:
#    urls: /user-balance-api/**
#
#springdoc:
#  api-docs:
#    path: /user-balance-api/v3/api-docs
#  swagger-ui:
#    path: /user-balance-api/swagger-ui.html
